---
# Configure rabbitmq servers.

- name: "Add square user."
  rabbitmq_user:
    user: square
    password: "martinet-ensign-gypsy-sorcery"
    permissions:
      - vhost: /
        configure_priv: .*
        read_priv: .*
        write_priv: .*
    state: present
  run_once: yes
  delegate_to: "{{ groups['rabbit'][0] }}"

- name: "Add (pan)opticon user."
  rabbitmq_user:
    user: pan
    password: "stickle-acclaim-wrongly-rhodesia-positive-muck"
    permissions:
      - vhost: /
        configure_priv: .*
        read_priv: .*
        write_priv: .*
    state: present
  run_once: yes
  delegate_to: "{{ groups['rabbit'][0] }}"

- name: "Remove the default guest user."
  rabbitmq_user:
    user: guest
    state: absent
  run_once: yes
  delegate_to: "{{ groups['rabbit'][0] }}"
